#!/usr/bin/env python3

"""
Created on 11 Feb 2026

@author: Bruno Beloff (bbeloff@me.com)

source repo: mrcs_test

DESCRIPTION
A tool that runs the MRCS services in test mode.

SYNOPSIS
mrcs_test_services [-h] [-v] [-t] [--version]

EXAMPLES
mrcs_test_services -v -t
"""

import sys

from mrcs_core.sys.logging import Logging
from mrcs_test.cli.args.services_args import ServicesArgs
from mrcs_test.internal.services import Services


# --------------------------------------------------------------------------------------------------------------------

if __name__ == '__main__':

    # ----------------------------------------------------------------------------------------------------------------

    args = ServicesArgs('runs the MRCS services in test mode')

    Logging.config('mrcs_test_services', verbose=args.verbose)
    logger = Logging.getLogger()
    logger.info(f'args: {args}')

    # ----------------------------------------------------------------------------------------------------------------

    try:
        Services.start(silent=not args.verbose, test_mode=args.test)
        Services.wait()

    # ----------------------------------------------------------------------------------------------------------------

    except KeyboardInterrupt:
        Services.stop()
        print(file=sys.stderr)
